create table [dbo].[ReadyCOR]
(	
	[Location Type] varchar(200),
	[Region] varchar(200),
	[Market] varchar(200),
	[District] varchar(200),
	[SAP & Store Name] varchar(1500),
	[SAP] varchar(100),
	[Employee ID #] varchar(100),
	[Employee Name] varchar(300),
	[Job Title] varchar(300),
	[Ready Program Status] varchar(200),
	[Curriculum Name] varchar(300),
	[Curriculum Status] varchar(200),
	[Curriculum Completion Rate] varchar(50),
	[Skill Set Score] float,
	[Provision Date] date,
	[Session Start Date] varchar(100),
	[Curriculum Completed Date] date,
	[Days Provisioned] int,
	[Weeks Provisioned] int,
	[Report Updated Timestamp] date,
	[Provision Month] varchar(100),
	[Provision Quarter] varchar(100),
	[Employee Tenure] varchar(300),
	[Training Session Status] varchar(100),
	[Registered for training session within 14 days?] varchar(100),
	[Completed Ready in 45 days from Session Start date?] varchar(100),
	[LastUpdateDate] date
)
